version: "3.8"
services:
  cloudreve:
    container_name: cloudreve
    image: cloudreve/cloudreve:latest
    restart: unless-stopped
    #ports:
      #- "5212:5212"            # 冒号左边的 5212 可以换成主机未被占用的端口
    volumes:
      - temp_data:/data
      - ./cloudreve/uploads:/cloudreve/uploads        # 冒号左边的这个可以换成你自己服务器的路径
      - ./cloudreve/conf.ini:/cloudreve/conf.ini      # 冒号左边的这个可以换成你自己服务器的路径
      - ./cloudreve/cloudreve.db:/cloudreve/cloudreve.db  # 冒号左边的这个可以换成你自己服务器的路径
      - ./cloudreve/avatar:/cloudreve/avatar
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - aria2
  
aria2:
    container_name: aria2
    image: ddsderek/aria2-pro
    restart: unless-stopped
    environment:
      - RPC_SECRET=your_aria_rpc_token_abcd  # 注意修改一下这个密钥
      - RPC_PORT=6800
      - DOWNLOAD_DIR=/data
      - PUID=0
      - PGID=0
      - UMASK_SET=022
      - TZ=Asia/Shanghai
    volumes:
      - ./aria2/config:/config    # 冒号左边的这个可以换成你自己服务器的路径
      - temp_data:/data

volumes:
  temp_data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/data
      o: bind
 
networks:
  default:
    external:
      name: cloudreve.io
